define(function () {
    return ''
    + '<div id=\'detailBox\'>\n'
    + '       \n'
    + '</div>\n'
    + '\n'
    + '<script type="text/tmeplate" id=\'detailBox_tpl\'>\n'
    + '    <div class="card">\n'
    + '        <% if(data.goods_images){ %>\n'
    + '            <img class="card-img-top" style="width:70%;align-self:center" src="http://127.0.0.1:8000/<%= data.goods_images  %>" />\n'
    + '        <% } %>\n'
    + '    \n'
    + '        <div class="card-body">\n'
    + '            <h4 class="card-title"><%= data.goods_name %></h4>\n'
    + '            <p class="card-text"><%= data.goods_title %></p>\n'
    + '\n'
    + '            <div class="clearfix" style="line-height:1.5rem;">\n'
    + '                <a  class="card-link float-left" style="font-size:1.5rem;color:#e4393c">¥\n'
    + '                    <%= data.goods_price %>\n'
    + '                </a>\n'
    + '                <a  class="card-link float-right" style="margin-top:0.3rem; font-size:0.8rem;color:#e4393c">\n'
    + '                    <i class="icon ion-bag"></i>购物车\n'
    + '                </a>\n'
    + '            </div>\n'
    + '        </div>\n'
    + '        \n'
    + '    </div>\n'
    + '    <div id="listBox"></div>\n'
    + '</script>\n'
    + '\n'
    + '<script type="text/tmeplate" id=\'listBox_tpl\'>\n'
    + '    <%_.each(list,function(item){%>\n'
    + '        <div class="col-md-3 col-lg-2 col-xl-2 float-left mt-1" style="padding:5;">\n'
    + '            <div class="card" data-id="<%=item.goods_id%>">\n'
    + '                <img class="card-img-top" src="http://127.0.0.1:8000/<%=item.goods_images%>" />\n'
    + '                <div class="card-body" style="padding:1rem">\n'
    + '                    <h4 class="card-title" style="font-size:1rem;height:2rem">\n'
    + '                        <%= item.goods_name %>\n'
    + '                    </h4>\n'
    + '                    <p class="card-text" style="font-size:0.5rem;height:1rem;line-height:1rem;">\n'
    + '                        <%= item.goods_title %>\n'
    + '                    </p>\n'
    + '                    <div class="clearfix" style="line-height:1.5rem;">\n'
    + '                        <a href="#" class="card-link float-left" style="font-size:1.5rem;color:#e4393c">¥\n'
    + '                            <%= item.goods_price %>\n'
    + '                        </a>\n'
    + '                        <a href="#" class="card-link float-right" style="margin-top:0.3rem; font-size:0.8rem;color:#e4393c">\n'
    + '                            <i class="icon ion-bag"></i>购物车</a>\n'
    + '                    </div>\n'
    + '                </div>\n'
    + '            </div>\n'
    + '        </div>\n'
    + '    <%})%>\n'
    + '</script>';
});